spring.application.name=note-seller-service
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

app.security.jwt.issuer=note-seller-service
app.security.jwt.expiration=PT2H
app.storage.s3.presign-expiration=PT15M
